name: Go

env:
  GIN_MODE: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v3

    # Step 1: Set up Go version 1.23 explicitly
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    # Step 2: Download Go modules
    - name: Download Go modules
      run: go mod download

    # Step 3: Revive Action for linting code
    - name: Revive Action
      uses: morphy2k/revive-action@v2.4.1

    # Step 4: Install and run Staticcheck with the latest compatible version
    - name: Staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@v0.5.1
        staticcheck ./...

    # Step 5: Build the project
    - name: Build
      run: go build -v ./...

    # Step 6: Install and run tests
    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@latest

    - name: Run tests
      run: |
        gotestsum --format=standard-verbose --junitfile=junit.xml

    # Step 7: Publish the test report
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/junit.xml'
        detailed_summary: true
        include_passed: true
